### ISSUE TITLE
Handle No Album Name When Taking A New Picture

### ISSUE THREAD

**Issue by derekdowling** [cs301w01/Skindex#66]
03-23 02:12:30.428: DEBUG/DBMANAGER(393): Raw query executed: SELECT _id FROM albums WHERE name = 'null'
03-23 02:12:30.447: ERROR/AndroidRuntime(393): FATAL EXCEPTION: main
        java.lang.NullPointerException
        at com.cs301w01.meatload.model.DBManager.selectIDByName(DBManager.java:267)
        at com.cs301w01.meatload.model.DBManager.selectAlbumIDByName(DBManager.java:281)
        at com.cs301w01.meatload.model.DBManager.insertPicture(DBManager.java:297)
        at com.cs301w01.meatload.controllers.PictureManager.savePicture(PictureManager.java:134)
        at com.cs301w01.meatload.controllers.PictureManager.takePicture(PictureManager.java:83)
        at com.cs301w01.meatload.activities.TakePictureActivity$3.onClick(TakePictureActivity.java:78)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:159)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3647)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by derekdowling** [comment]
This might only be a problem in our placeholder screen. The Take Picture button really won't be present in the real deal right? Only the "New Album" button?

**Comment by joelburford** [comment]
No, I think the plan was to have a take picture button, and when an album isn't selected you prompt for one or something like that.

**Comment by derekdowling** [comment]
Dealt with, user either picks a new album or selects an existing one.
